target-version = "py311"
line-length = 120

[lint]
select = ["E", "F", "I", "N", "W", "UP"]
ignore = ["E501"]

[lint.per-file-ignores]
"tests/**" = ["E402", "F401", "F841", "F541"]
"scripts/**" = ["E402", "F401"]

[format]
quote-style = "double"
indent-style = "space"
