"""create authorization tables

Revision ID: 272915ecc478
Revises: 
Create Date: 2026-09-25 23:21:25.454397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272915ecc478'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Enum('vehicle_user', 'workshop_owner', 'maintenance_staff', name='role_code_enum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('vehicle_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('external_owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='user_status_enum'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_vehicle_user_email'), 'vehicle_user', ['email'], unique=True)
    op.create_index(op.f('ix_vehicle_user_firebase_uid'), 'vehicle_user', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_vehicle_user_phone'), 'vehicle_user', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_user_phone'), table_name='vehicle_user')
    op.drop_index(op.f('ix_vehicle_user_firebase_uid'), table_name='vehicle_user')
    op.drop_index(op.f('ix_vehicle_user_email'), table_name='vehicle_user')
    op.drop_table('vehicle_user')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
